spring:
  # 메일 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
      company-name: Hero Factory
    protocol: smtp

  # NCloud SMS 설정
  cloud:
    ncp:
      sms:
        enabled: false

  # Swagger 설정
  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html
      tags-sorter: alpha
      operations-sorter: alpha
    packages-to-scan: ai.herofactoryservice

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    defer-datasource-initialization: true
    sql:
      init:
        mode: always
        schema-locations: classpath:./postgresql/init/init.sql
        continue-on-error: false

  elasticsearch:
    uris: http://localhost:9200

  # 데이터소스 설정
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver


  # RabbitMQ 설정
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}

  # Redis 설정
  data:
    redis:
      host: redis
      port: 6379
      password: ${REDIS_PASSWORD}

# 서버 설정
server:
  port: ${SERVER_PORT}

# JWT 설정
jwt:
  secret-key: ${JWT_SECRET_KEY}

# OpenAI 설정
openai:
  api:
    key: ${OPENAI_API_KEY}
    base-url: https://api.openai.com/v1
    models:
      chat: ${OPENAI_MODEL_CHAT}
      embedding: ${OPENAI_MODEL_EMBEDDING}
    request:
      timeout: ${OPENAI_REQUEST_TIMEOUT}
      max-tokens: ${OPENAI_REQUEST_MAX_TOKENS}
      temperature: ${OPENAI_REQUEST_TEMPERATURE}
      connect-timeout: ${OPENAI_REQUEST_CONNECT_TIMEOUT}
    rate-limit:
      requests-per-minute: 20  # 직접 값 설정
      burst: 5  # 직접 값 설정
# 카카오 설정
kakao:
  client:
    id: ${KAKAO_CLIENT_ID}
  pay:
    admin:
      key: ${KAKAO_PAY_ADMIN_KEY}
    cid: ${KAKAO_PAY_CID}

# 결제 재시도 설정
payment:
  retry:
    max-attempts: 3
    delay-minutes: 240  # 4시간

# CORS 설정
cors:
  allowed-origins: http://localhost:3000