spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/hero_factory_db
    username: postgres
    password: himedia1!
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

openai:
  api:
    key: ${OPENAI_API_KEY}
    base-url: https://api.openai.com/v1
    models:
      chat: gpt-3.5-turbo
      embedding: text-embedding-3-small
    request:
      timeout: 60000
      max-tokens: 204
      temperature: 0.7
    rate-limit:
      requests-per-minute: 20  # 분당 최대 요청 수
      burst: 5                 # 버스트 허용량