spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/hero_factory_db
    username: postgres    # 실제 DB 사용자명으로 교체
    password: himedia1!    # 실제 DB 비밀번호로 교체
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
  rabbitmq:
    username: guest
    password: guest

kakao:
  pay:
    admin:
      key: 50cffe5817e980757926f92113d0b6f1    # 테스트용 Admin key
    cid: TC0ONETIME     # 테스트용 CID

    openai:
      api-key: your-api-key-here  # 실제 API 키로 교체 필요
      model: gpt-4
      embedding-model: text-embedding-3-small
      max-tokens: 2048
      temperature: 0.7
