kakao:
  client:
    id: ${KAKAO_CLIENT_ID}

spring:
  application:
    name: hero-factory-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect


logging:
  level:
    ai:
      herofactoryservice: DEBUG