spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/hero_factory_db
    username: postgres    # 실제 DB 사용자명으로 교체
    password: himedia1!    # 실제 DB 비밀번호로 교체
  rabbitmq:
    username: guest
    password: guest

kakao:
  pay:
    admin:
      key: TC0ONETIME    # 테스트용 Admin key
    cid: TCSUBSCRIP     # 테스트용 CID
