spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/hero_factory_db
    username: postgres
    password: himedia1!
    driver-class-name: org.postgresql.Driver
    # Connection Pool 설정 추가
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # pgvector 관련 설정
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50

  rabbitmq:
    username: guest
    password: guest

# OpenAI API 설정 상세화
openai:
  api:
    key: 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
    base-url: https://api.openai.com/v1
    models:
      chat: gpt-4
      embedding: text-embedding-3-small
    request:
      timeout: 60000
      max-tokens: 2048
      temperature: 0.7
      top-p: 1.0
      frequency-penalty: 0.0
      presence-penalty: 0.0
    retry:
      max-attempts: 3
      initial-interval: 1000
      multiplier: 2.0
      max-interval: 10000

kakao:
  pay:
    admin:
      key: 50cffe5817e980757926f92113d0b6f1
    cid: TC0ONETIME