server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

logging:
  level:
    ai.herofactoryservice: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO
    org.springframework.ai: DEBUG