package com.herofactory.kafka.inspecteditem;

import com.herofactory.inspecteditem.dto.InspectedItemDto;
import com.herofactory.shop.dto.ItemDto;
import java.time.LocalDateTime;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@NoArgsConstructor
@Data
public class InspectedItemMessage {
    private Long id;
    private Payload payload;

    @AllArgsConstructor
    @NoArgsConstructor
    @Data
    public static class Payload {
        private ItemDto itemDto;
        private List<String> autoGeneratedTags;
        private LocalDateTime inspectedAt;
    }

    public InspectedItemDto toModel() {
        return new InspectedItemDto(
                payload.getItemDto(),
                payload.getAutoGeneratedTags(),
                payload.getInspectedAt()
        );
    }
}
