spring:
  application:
    name: create-game-resource-service
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 5000
          max-attempts: 3
          multiplier: 1.0
          max-interval: 10000
        default-requeue-rejected: false
    connection-timeout: 5000
    requested-heartbeat: 60
  web:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:8080}
      allowed-methods: GET, POST, PUT, DELETE, OPTIONS
      allowed-headers: '*'
      allow-credentials: true

server:
  port: ${SERVER_PORT:8288}

logging:
  level:
    org.springframework.amqp: DEBUG
    com.gameservice: DEBUG

supabase:
  url: ${SUPABASE_URL}
  key: ${SUPABASE_KEY}
  secret: ${SUPABASE_SECRET}

fastapi:
  url: ${FASTAPI_URL:http://localhost:8000}