spring:
  rabbitmq:
    username: guest
    password: guest

supabase:
  url: https://fztbzrknyjvvktznmcgt.supabase.co
  key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6dGJ6cmtueWp2dmt0em5tY2d0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mjg5NTg5MTYsImV4cCI6MjA0NDUzNDkxNn0.QRIxpq-PLyklHJUcE0YOkZhYE3BXgrtrWX6735rq1gM
  secret: himedia241015$